"""add post image fields

Revision ID: cc625ed29a9c
Revises: 120e1000d95a
Create Date: 2026-08-16 12:53:43.074326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc625ed29a9c'
down_revision: Union[str, Sequence[str], None] = '120e1000d95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('image_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_public_id')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
